# Site settings
title: Jekyll Template
email: dev@pitple.com
description: Jekyll Template 
baseurl: "/jekyll-template" 
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
destination: docs
timezone: Asia/Seoul
markdown: kramdown
exclude: [.gitignore, README.md, LICENCE, jk-run.bat, jk-build.bat, jk-push.bat]
include: [.nojekyll]

# Gems
gems:
  - github-pages
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin
languages: ["en", "ko"]
exclude_from_localizations: ["javascript", "images", "css"]