# Site settings
title: Jekyll Template
email: dev@pitple.com
description: Jekyll Template 
baseurl: "/jekyll-template"
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
destination: docs
timezone: Asia/Seoul
markdown: kramdown
include: [.nojekyll]
exclude: [docs, .gitignore, README.md, vendor, .travis.yml]

# Gems
gems:
  - github-pages
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin
languages: ["en", "ko"]
exclude_from_localizations: ["javascript", "images", "css"]